apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: infra
type: Opaque
data:
  user: bWluaW9hZG1pbg==
  password: bWluaW9hZG1pbg==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: infra
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2022-10-08T20-11-00Z
        ports:
        - containerPort: 9000
          name: web
        - containerPort: 9090
          name: console
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: password
        volumeMounts:
        - mountPath: /data
          name: minio-data
        command:
        - minio
        - server
        - /data
        - --console-address
        - ":9090"
      volumes:
      - name: minio-data
        hostPath:
          path: /data/minio
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: infra
  labels:
    app: minio
spec:
  ports:
  - port: 9000
    name: web
  - port: 9090
    name: console
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: infra
spec:
  rules:
  - host: "minio.localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port:
              number: 9090
